//package prir.zad7;
/**
* optimizationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from generator.idl
* Tuesday, June 2, 2015 7:40:42 PM CEST
*/

public interface optimizationOperations 
{
  void register (short ip, int timeout, org.omg.CORBA.IntHolder id);
  void hello (int id);
  void best_range (rangeHolder r);
} // interface optimizationOperations
