
/**
* optimization.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from generator.idl
* Tuesday, June 2, 2015 7:40:42 PM CEST
*/

public interface optimization extends optimizationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface optimization
